#!/bin/bash
# Running Gramado OS on qemu with kvm accel

# Common
GRAMADO_CPUS="2"
GRAMADO_RAM_SIZE="512"
GRAMADO_DISK_IMAGE="GRAMHV.VHD"

QEMU="qemu-system-x86_64"

set -e

# Exit the script.
die(){
	echo "die: "
	exit 1
}

# Hello!
	echo "~~~~>"

#	-netdev type=user,id=net1 -device e1000,netdev=net1

# Launch qemu application.
# Order: CPU, RAM, DISK, DEVICES.
	$QEMU \
	-smp $GRAMADO_CPUS \
	-machine pc \
	-m   $GRAMADO_RAM_SIZE \
	-hda $GRAMADO_DISK_IMAGE \
	-serial stdio

# Exit the script.
	die
