

all:

	make -C libs/rtl/

# Gramado X Window System
# Client-side library for the Display server.
# Using a modifield version on old X protocol
	make -C libs/libx/

	make -C xtb/

clean:
	-rm bin/*.BIN 

