# Codename: Summer
# Created by Fred Nora.

all:
	make -C core/
	make -C heavy/

clean:
	-rm -f *.o
	-rm -f bin/*.BIN
clean-all:
	-rm -f *.o
	-rm -f bin/*.BIN
	-rm -f libs/libgns/obj/*.o
	-rm -f libs/rtl/obj/*.o

