# Build the all in windows/.
# Provide windows for the apps.

all:
# Display server and libraries
	make -C ds3d/

clean:
# Display server and libraries
	-rm ds3d/demo00/*.o
	-rm ds3d/demo00/bin/*.BIN
	-rm ds3d/demo01/*.o
	-rm ds3d/demo01/bin/*.BIN

clean-all:
# Display server and libraries
	-rm ds3d/demo00/*.o
	-rm ds3d/demo00/bin/*.BIN
	-rm ds3d/demo01/*.o
	-rm ds3d/demo01/bin/*.BIN
